type: lamp
dist: ubuntu
php: 8.5
database: mysql:8.4
solr: 8.11.4

steps:
  - name: Testing
    plugin: LAMPApp
    phpIniOptions:
      memory_limit: 512M
      max_execution_time: 300
    subDirectory: src
