type: lamp
dist: ubuntu
php: 7.0
database: mysql:5.7
solr:
  name: drupal
  version: 8.11.4
  core: /path/to/core

steps:
  - name: Testing
    plugin: LAMPApp
    phpIniOptions:
      memory_limit: 512M
      max_execution_time: 300
    subDirectory: src
