assets:
  - solr8.zip
type: lamp
dist: ubuntu
php: 8.5
nodejs: 24
database: mariadb:11.8

steps:
  - name: Testing
    plugin: LAMPApp
    phpIniOptions:
      memory_limit: 512M
      max_execution_time: 300
    subDirectory: src
