type: lamp
dist: ubuntu
php: 8.2
database: mariadb:11.8
solr:
  name: drupal
  version: 8.11.4
  core_archive: solr8.zip
  core_folder: solr8
  compression: zip

steps:
  - name: Testing
    plugin: LAMPApp
    phpIniOptions:
      memory_limit: 512M
      max_execution_time: 300
    subDirectory: src
