
type: lamp
dist: ubuntu
php: '8.2'
database: mariadb:11.4

steps:
  - name: Testing
    plugin: LAMPApp
    phpIniOptions:
      memory_limit: 512M
      max_execution_time: 300
    subDirectory: src
